version: 2.1

orbs: 
  browser-tools: circleci/browser-tools@1.2.5

jobs:
  test:
    machine:
      image: ubuntu-2004:2022.04.2 # recommended linux image
    resource_class: 2xlarge
    steps:
      - browser-tools/install-chrome

workflows:
  damain:
    jobs:
      - test
